# 次のDDLにてDBを作成しておく
# CREATE DATABASE personal_dev_11761_oka_narumi OWNER postgres ENCODING 'UTF8';

# DB接続情報
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/personal_dev_11761_oka_narumi
spring.datasource.username=postgres
spring.datasource.password=0001

# SQL実行出力
spring.jpa.show-sql=true
# schema.sqlとdata.sqlの自動実行
spring.sql.init.mode=always
